-- PhD Terminal Supabase Veritabani Kurulumu --
-- Bu kodlari Supabase > SQL Editor icine yapistirip calistirin.

-- 1. FAVORILER TABLOSUNA (favorites)
CREATE TABLE IF NOT EXISTS public.favorites (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  symbol TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  
  -- Bir kullanici ayni hisseyi sadece bir kez favoriye alabilir
  UNIQUE(user_id, symbol)
);

-- 2. GUVENLIK AYARLARI (Row Level Security - RLS)
ALTER TABLE public.favorites ENABLE ROW LEVEL SECURITY;

-- 3. POLITIKALAR (Kim neyi gorebilir/yapabilir?)
-- Sadece kendi favorilerini okuma
CREATE POLICY "Users can view their own favorites" 
ON public.favorites FOR SELECT 
USING (auth.uid() = user_id);

-- Sadece kendi favorilerini ekleme/cikarma
CREATE POLICY "Users can insert their own favorites" 
ON public.favorites FOR INSERT 
WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can delete their own favorites" 
ON public.favorites FOR DELETE 
USING (auth.uid() = user_id);

-- 4. OTOMATIK PROFIL OLUSTURMA (Opsiyonel ama onerilir)
-- auth.users'a yeni biri kayit oldugunda public.profiles'a da ekleyelim (istege bagli)
-- Simdilik favoriler tablosu ana ihtiyacimiz.
